---
development:
  DB_KEY: <replace with crypto key `rake generate:db_key`>
  MSG_KEY: <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: <provision key from SendGrid>

test:
  DB_KEY: <replace with crypto key `rake generate:db_key`>
  MSG_KEY: <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: <provision key from SendGrid>

production:
  DB_KEY: <replace with crypto key `rake generate:db_key`>
  MSG_KEY: <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: <provision key from SendGrid>